use_frameworks!

target 'SwiftPrelude_Example' do
  pod 'SwiftPrelude', :path => '../'

  target 'SwiftPrelude_Tests' do
    inherit! :search_paths
    pod 'SwiftPrelude', :path => '../'
    
  end
end
